swagger: '2.0'
info:
  title: api.hebe.io
  description: Manage Images in the Cloud
  version: "1.0.0"
host: api.hebe.io
schemes:
  - https

securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: X-API-Key

paths:
  /img/{userid}/{filename}:
    put:
      security:
       - ApiKeyAuth: []
      description: upload file
      summary: Upload file to the cloud storage
      tags:
        - modify
      parameters:
        - in: path
          name: userid
          description: user id.
          required: true
          type: string
          minLength: 7
        - in: path
          name: filename
          description: name of the file which will be uploaded.
          required: true
          type: string
          minLength: 5
      responses:
        '200':
          description: the file has been uploaded successfully.
    get:
      description: download file
      summary: download file from the cloud storage
      tags:
        - view
      parameters:
        - in: path
          name: userid
          description: user id.
          required: true
          type: string
          minLength: 7
        - in: path
          name: filename
          description: name of the file which will be downloaded.
          required: true
          type: string
          minLength: 5
      responses:
          '200':
            description: Return file.
    delete:
      security:
       - ApiKeyAuth: []
      description: delete file
      summary: delete a single file from the cloud storage
      tags:
        - modify
      parameters:
        - in: path
          name: userid
          description: user id.
          required: true
          type: string
          minLength: 7
        - in: path
          name: filename
          description: name of the file which will be deleted.
          required: true
          type: string
          minLength: 5
      responses:
        '200':
          description: The File has been deleted successfully.

  /img/{userid}:
    get:
      security:
       - ApiKeyAuth: []
      description: list files
      summary: List all file under a certain user folder on the cloud storage
      tags:
        - view
      parameters:
        - in: path
          name: userid
          description: user id.
          required: true
          type: string
          minLength: 7
        - in: query
          name: offset
          type: integer
          required: false
          description: The number of items to skip before starting to collect the result set.
        - in: query
          name: limit
          type: integer
          required: false
          description: The numbers of items to return.
      responses:
        '200':
          description: list files successfully.
